# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :register_app do
    produce(
	username: "gokhandidin@outlook.com",
	app_identifier: "gokhandidin.AppcentNewsApp",
	app_name: "AppcentNewsApp"
    )
  end

  lane :get_dev_certs do
    cert(
	development: true
    )
    sigh(
	development: true
    )
  end

end
